### PR TITLE
#2241 Refactor the updateState for all cluster routes

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2241)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@wu87988622 This is another issue about streamapp. Please merge it if QA does not complain.

**Comment by wu87988622** [comment]
> @wu87988622 This is another issue about streamapp. Please merge it if QA does not complain.

OK thanks for fix bug.

**Comment by chia7712** [comment]
@wu87988622 Please take a look at this PR. thanks

**Comment by wu87988622** [comment]
> @wu87988622 Please take a look at this PR. thanks

@chia7712  QA is stuck?

**Comment by chia7712** [comment]
> QA is stuck?

oh...Let me restart QA.

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry configurator

**Pull request merged**
