### PR TITLE
Update logs, pipeline, and work list page APIs

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

required by #298

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
有找到 build failed 的原因了, 主要是在跑 QA 時, 再進入 container 之前會先做 yarn 的檢查, 因此除了 docker image 需要安裝 yarn 之外, 跑 QA 的實體機也要安裝 yarn.

**Comment by konekoya** [comment]
> 有找到 build failed 的原因了, 主要是在跑 QA 時, 再進入 container 之前會先做 yarn 的檢查, 因此除了 docker image 需要安裝 yarn 之外, 跑 QA 的實體機也要安裝 yarn.

So we have to upgrade each node (VM)'s yarn manually QQ?

**Comment by konekoya** [comment]
retry manager

**Comment by chia7712** [comment]
嗯...我們應該把測試build也放到container裡面...

**Comment by jackyoh** [comment]
> 試build也放到container裡面...

所以在前面那一段(check compilation)可以先 -PskipManager 嗎？

**Comment by vitojeng** [comment]
> 嗯...我們應該把測試build也放到container裡面...

Docker 萬歲!

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
retry agent

**Comment by chia7712** [comment]
我已經把"所有檢查"都放到container裡面去執行了，所以不用在jenkins節點上安裝有的沒的了 FYI @jackyoh

**Comment by konekoya** [comment]
Thanks for the help @chia7712 @jackyoh :)

**Comment by jackyoh** [comment]
@chia7712 Thank you

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Pull request merged**
