### PR TITLE
#1643 Remove ID from ohara

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1643)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by chia7712** [comment]
@wu87988622 @konekoya Do you have cycle to complete this PR together?

**Comment by wu87988622** [comment]
> @wu87988622 @konekoya Do you have cycle to complete this PR together?

I will finish this PR together.

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
@wu87988622 any update? There are many issues blocked by this one :(

**Comment by konekoya** [comment]
@chia7712 I'll be working on this as I'm a bit more familiar with the pipeline logic

**Comment by chia7712** [comment]
> I'll be working on this as I'm a bit more familiar with the pipeline logic

please fill "konekoya" in the "Assignee" field :)

**Comment by konekoya** [comment]
> please fill "konekoya" in the "Assignee" field :)

Done :)

**Comment by konekoya** [comment]
retry manager-api

**Comment by konekoya** [comment]
retry manager-it

**Comment by konekoya** [comment]
retry manager-api

**Comment by chia7712** [comment]
retry configurator

**Comment by konekoya** [comment]
retry manager-it

**Comment by konekoya** [comment]
retry manager-it

**Comment by chia7712** [comment]
great!!!!!!!

**Pull request merged**
