### PR TITLE
OHARA-1615 Log APIs should use url-path to replace query parameter

### PR DESCRIPTION
**Pull request by chia7712**

### CODE REVIEW

**Comment by chia7712** [comment]
@konekoya @eechih 我給前端的檔案加了一些註解，麻煩看看我有沒有把代碼弄得醜醜

**Comment by konekoya** [comment]
Comments looks fine. Harry, could you please take a quick look at this PR (would be best if you can manage to test it on your local machine) See if it breaks anything in the front end? Thanks :)

**Comment by konekoya** [comment]
Should have asked this first... @chia is this backward compatible 😅

**Comment by chia7712** [comment]
> Should have asked this first... @chia is this PR backward compatibl

of course. I had test it by previous APIs on local. BTW, I tried to add comments to manager, but seems we don’t use this cluster name of log API currently.

**Comment by chia7712** [comment]
@eechih This PR needs your bless!

**Comment by vitojeng** [comment]
@konekoya 你 ping 錯人了喔...還是為了要讓更多人知道 ohara? XD

**Comment by chia7712** [comment]
> 你 ping 錯人了喔...還是為了要讓更多人知道 ohara? XD

@konekoya 你一定是用手機敲那段訊息

**Comment by konekoya** [comment]
沒錯，XXD, 手機 @ 人超難用的，而且我忘了我可以用中文輸入法。。。基本上我是+1, 但想說還是再麻煩志強幫忙測一下比較好喔 :)

**Comment by eechih** [comment]
> @konekoya @eechih 我給前端的檔案加了一些註解，麻煩看看我有沒有把代碼弄得醜醜

Look fine to me. 😀

**Comment by chia7712** [comment]
@eechih thanks for reviews!

**Pull request merged**
