### PR TITLE
#448 upload jars to jfrog for 0.2 release

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] Set a Milestone (we usually file PR for master branch)
- [x] Link to an issue(You can do so by using the required by keyword: required by #448)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
IIRC, we file a PR after opening a issue?

**Comment by saivirtue** [comment]
This PR could not run normally in our jenkins (I think we use the master as the base branch, right?)
just want some check inside this PR...I will close this PR after push to 0.2 branch

**Comment by saivirtue** [comment]
> IIRC, we file a PR after opening a issue?

And we don't haveM25(v0.2) milestone anyway...

**Comment by chia7712** [comment]
> I think we use the master as the base branch, right?

我們可以提早支援這個，為維護branch做準備 @jackyoh any suggestions?

**Comment by chia7712** [comment]
> And we don't have M25(v0.2) milestone anyway...

Could we have another milestone for other active branch?

**Comment by vitojeng** [comment]
> > And we don't have M25(v0.2) milestone anyway...
> 
> Could we have another milestone for other active branch?

Sure. Let us think a good name for these milestone...

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
關於開 PR 使用不同 branch 的部份, 我已經用好了, 但是在 0.2 版有一個 check java doc 的部份需要 @saivirtue  的支援

**Comment by saivirtue** [comment]
retry

**Comment by saivirtue** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
K8S 的錯誤先不用理會，可能是環境的問題，目前正在解環境的問題。

**Comment by saivirtue** [comment]
retry configurator

**Comment by saivirtue** [comment]
it測試除了K8S的失敗外，其他失敗的與it節點沒有0.2.1的image有關

**Comment by chia7712** [comment]
如果可以的話，盡量讓commit保持獨立會比較好連結（例如我們將在#413增加修訂版本0.2.1，並且連結到某個修復docs的PR)

**Comment by saivirtue** [comment]
> 如果可以的話，盡量讓commit保持獨立會比較好連結（例如我們將在#413增加修訂版本0.2.1，並且連結到某個修復docs的PR)

好，我把兩個commit 都獨立出來

**Pull request closed without merging**
