### PR TITLE
#1656 Replace JsArray() by JsArray.empty 

### PR DESCRIPTION
**Pull request by dc-tw**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1656)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by dc-tw** [comment]
This PR contains the last PR's commit. My fault.

**Comment by chia7712** [comment]
@dc-tw 你是不是提交了奇怪的東西上來？

BTW, 麻煩從最新的master branch開新的branch來完成此PR喔

**Comment by chia7712** [comment]
@dc-tw 如果你是用vscode來開發的話，麻煩把.vscode加到gitignore裡面

**Comment by dc-tw** [comment]
對 我正在嘗試解決, 應該晚上可以修正這錯誤

**Comment by dc-tw** [comment]
rebase 完成, 再麻煩幫我review

**Comment by dc-tw** [comment]
@chia7712 抱歉我還跟jenkins不熟
上次推完後我有繼續看其他issue, 但沒看到比較熟悉的項目所以最後選了這個good first issue
有按照步驟安裝在電腦, 但實際的issue要如何操作還不確定, 所以我在思考怎麼繼續貢獻

**Comment by chia7712** [comment]
@dc-tw 你不用跟jenkins混熟了，比較重要的流程是接issue 開PR reviews rebase等等

流程熟了之後就可以開始找一些比較深入的議題挑戰看看

**Comment by dc-tw** [comment]
了解 我會繼續關注issue

**Comment by chia7712** [comment]
@dc-tw 下次記得把checklist裡面確認完成的項目打勾

**Comment by vitojeng** [comment]
Good job! Thanks @dc-tw for the PR!

**Pull request merged**
