### PR TITLE
#1972 Apply "start" and "stop" action to Topic API with Ohara Manager

### PR DESCRIPTION
**Pull request by wu87988622**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1972 )
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-api

**Comment by konekoya** [comment]
@wu87988622 I keep getting the error while running API test (in browser mode) in my local, but it seems like it works okay on QA. Do you know why it's happening?


The error I keep getting:
```
Cannot delete jar [ohara-it-source.jar] which is in used
```

**Comment by wu87988622** [comment]
> @ wu87988622我在本地運行API測試（在瀏覽器模式下）時遇到以下錯誤，但似乎它在QA上運行正常。你知道為什麼會這樣嗎？
> 
> 我一直得到的錯誤：
> 
> ```
> Cannot delete jar [ohara-it-source.jar] which is in used
> ```

This error is in worker?? In my local not have is error.

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
> This error is in worker?? In my local not have this error.
My configurator is use docker image, not use source code build, maybe different is in this?

Hmm, I"m using docker image too. It's very odd, I was thinking maybe it's due to some API changes. If it can't repro in your env, it could have something to do with my env

1.

**Comment by chia7712** [comment]
Could you share the requests to me?thanks!

**Comment by konekoya** [comment]
Req: `http://localhost:3000/api/files/ohara-it-source.jar?group=default`
Res:
```js
The response we got was:

Status: 500 - Server Error
Headers: {
  "x-powered-by": "Express",
  "server": "akka-http/10.1.3",
  "date": "Sat, 03 Aug 2019 22:17:07 GMT",
  "connection": "close",
  "content-type": "application/json",
  "content-length": "822",
  "vary": "Accept-Encoding"
}
Body: {
  "code": "java.lang.RuntimeException",
  "message": "Cannot delete jar [ohara-it-source.jar] which is in used",
  "stack": "java.lang.RuntimeException: Cannot delete jar [ohara-it-source.jar] which is in used\n\tat com.island.ohara.configurator.route.FileRoute$.$anonfun$route$13(FileRoute.scala:90)\n\tat com.island.ohara.configurator.route.FileRoute$.$anonfun$route$13$adapted(FileRoute.scala:89)\n\tat scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)\n\tat scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)\n\tat scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
}
```

Thanks for the help :)

**Comment by chia7712** [comment]
Is the jar file used by streamapp? Currently, we reject the deletion of file only if the file is used by streamapp.

**Comment by konekoya** [comment]
> Is the jar file used by streamapp? Currently, we reject the deletion of file only if the file is used by streamapp.

Yes, that's why we couldn't delete the jar. Thank you so much @chia7712 :)

**Pull request merged**
