### PR TITLE
#4091 Manager crashed by an infinite loop

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4091)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
retry manager-e2e

**Comment by saivirtue** [comment]
retry manager-e2e

**Comment by saivirtue** [comment]
retry manager-e2e

**Comment by saivirtue** [comment]
The failed test was not related to this PR.

**Comment by saivirtue** [comment]
@chia7712 
Please help me to merge this PR, appreciate it :)

**Comment by chia7712** [comment]
Is the flaky related to this PR?

**Comment by saivirtue** [comment]
> Is the flaky related to this PR?

Nope. The failed test was because there are some other e2e tests running on the same node.

**Pull request merged**
