### PR TITLE
#5030 [Manager] Remind users whether the file to be deleted is used b…

### PR DESCRIPTION
**Pull request by eechih**
…y the pipeline

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #5030 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by eechih** [comment]
retry manager-e2e

**Comment by eechih** [comment]
@chia7712 由於 pipeline 沒有直接使用 shared jar 的 class，無法反向查找 shared jar 是否被使用，因此 remove shared jar 就沒有移除警示。

Stream jar 及 plugin jar 如果被 pipeline 使用，當使用者要移除 jar 時，會警示如下：

螢幕快照 2020-05-26 上午6 58 56

**Comment by chia7712** [comment]
> 由於 pipeline 沒有直接使用 shared jar 的 class，無法反向查找 shared jar 是否被使用，因此 remove shared jar 就沒有移除警示。

考慮到share jar裡面放的connector也會出現在worker的connector列表裡面，移除share jar的時候可能也要inspect一下然後看一下是否有connector

**Comment by eechih** [comment]
@konekoya 請問放在 sharedJarKeys 的 jar 裡面的 connector 會被載入 Toolbox 嗎？

**Comment by konekoya** [comment]
> @konekoya 請問放在 sharedJarKeys 的 jar 裡面的 connector 會被載入 Toolbox 嗎？

We're currently loading all connectors from the classInfos of inspect worker...

**Comment by eechih** [comment]
> We're currently loading all connectors from the classInfos of inspect worker...

Got it. Thanks @konekoya 

> 考慮到share jar裡面放的connector也會出現在worker的connector列表裡面，移除share jar的時候可能也要inspect一下然後看一下是否有connector

@chia7712 No problem

**Comment by eechih** [comment]
retry manager-e2e

**Pull request merged**
