### PR TITLE
#1362 Implement exactly once for streamApp

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1362)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by saivirtue** [comment]
> @saivirtue Please take a look at #1479.
> 
> Exactly once is a great feature to ohara. But, we should enhance our collie before adding more black box to collie. Is our streamapp either exactly once or exactly nothing? I don't think so. A switch button used to switch the different mode is ok to UI. However, as a strong backend, we should have more flexible, custom, and graceful **options** to our API than just a **flag**.
> 
> This PR can be merged first, and then we should file a large issue to discuss
> 
> 1. how to expose the configs of collie via APIs and
> 2. how to put those configs on UI

OK, the further discussion move to #1479.
The failed case is traced on #1417, going to merge this pr.

**Pull request merged**
