### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by konekoya**
# This is a PR testing manager's end-to-end test. Please don't do the review or merge it...

### Checklist
- [ ] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [ ] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [ ] Add Assignees (of course, you are the assignee by default!)
- [ ] DON'T set a Milestone
- [ ] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [ ] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager-it

**Comment by chia7712** [comment]
seems the build of manager module is failed. see [report](https://builds.is-land.com.tw/job/PreCommit-OHARA/3159/artifact/checks/check_build.log)

**Comment by konekoya** [comment]
> seems the build of manager module is failed. see report

Ah, good catch. Forgot that adding new lines breaks the build as well  😅

**Comment by konekoya** [comment]
Looks like the failing test is a causing in topics test. Will fix this in #1650

**Pull request closed without merging**
