### PR TITLE
#1221 Upload metrics jar to maven repo (backport to 0.4)

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1221)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
This issue only change gradle file
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@saivirtue Please file a PR for master as well

**Comment by saivirtue** [comment]
> @saivirtue Please file a PR for master as well

Uh...[here it is](https://github.com/oharastream/ohara/pull/1222)

**Comment by chia7712** [comment]
@konekoya Please merge this one and then confirm #1226 as soon as possible.

**Comment by konekoya** [comment]
> @konekoya Please merge this one and then confirm #1226 as soon as possible.

Will do

**Pull request merged**
