### PR TITLE
test jenkins

### PR DESCRIPTION
**Pull request by chia7712**
FOR TESTING

**DO NOT COMMIT THIS PR!!!**

### CODE REVIEW

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
@oharastream/developer the check to document files is already integrated to our QA. please take a look.

**Comment by saivirtue** [comment]
Does this jenkins test integrate both `javadoc` and `rst` check result?

**Comment by vitojeng** [comment]
@chia7712 Great work!
似乎沒有看到 docs build 的 log?

**Comment by vitojeng** [comment]
抱歉, 我看到了~

**Comment by chia7712** [comment]
> Does this jenkins test integrate both javadoc and rst check result?

both checks (javadocs and document files) are reported via "build" status.

**Comment by vitojeng** [comment]
想到一個建議: 目前 checks 裡有分不同的區塊, 如：
> v  build
> v  build images
> x  test/agent
> ...

是否可以 docs 也有一個獨立的 check 區塊?

**Comment by chia7712** [comment]
> 是否可以 docs 也有一個獨立的 check 區塊?

本來獨立的區段用意是放一些跑比較久的檢查 同時允許retry 
現在build docs實在太快了 所以才整併到build階段去

**Comment by vitojeng** [comment]
了解

**Comment by chia7712** [comment]
Let me close this now. Thanks for all reviewers :)

**Pull request closed without merging**
