### PR TITLE
#4491 Update gradle from 5.6.4 to 6.3.0

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4491)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
It seems the duration of compiling scala get slower on gradle 6.

ping @oharastream/developer. Could you build ohara with this PR on your local? The steps are shown below.

1. apply this PR
1. download gradle 5.6.4 and build ohara ```gradle-5.6.4/bin/gradle clean build -x test -PskipManager'''
1. download gradle 6.3.0 and build ohara ```gradle-6.3/bin/gradle clean build -x test -PskipManager'''

I use both gradle 5.6.4 and gradle 6.3 to build both ohara and kafka. It seems gradle 6.3 get slower build. More details is that only scala module get slower build. the duration of building java module is almost same.

**Comment by chia7712** [comment]
The slow duration is harmless I'd say as the the slowest tasks in our QA are tests.

**Comment by jackyoh** [comment]
我明天早上使用我的 local 來測試看看

**Comment by chia7712** [comment]
it seems the new zinc (https://docs.gradle.org/current/userguide/scala_plugin.html#sec:configure_zinc_compiler) needs more time to analyze source code to address incremental compilation.

**Comment by chia7712** [comment]
retry

**Comment by jackyoh** [comment]
我有把這個 branch 拉下來測試，但是 build.gradle 第 137 行有錯誤。訊息如下：
```
Starting a Gradle Daemon, 1 busy and 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/home/user1/chia7712/ohara/build.gradle' line: 137

* What went wrong:
A problem occurred evaluating root project 'ohara'.
> Could not find method scala() for arguments [build_7rqa9esbl6l1fdx8q097lz05d$_run_closure4$_closure10@d793d2c] on project ':ohara-agent' of type org.gradle.api.Project.
```

**Comment by chia7712** [comment]
> 我有把這個 branch 拉下來測試，但是 build.gradle 第 137 行有錯誤。訊息如下：

你是用gradle 5.x遇到這個問題的吧?

**Comment by jackyoh** [comment]
> 你是用gradle 5.x遇到這個問題的吧?

對，我是用 5.6.4  跑遇到的問題。

**Comment by chia7712** [comment]
> 對，我是用 5.6.4 跑遇到的問題。

看來新版的zinc設定沒有向下相容

那可否麻煩你直接用gradle 5.x建置master，然後與用gradle 6.x+此PR建置專案 兩個時間比較一下?

**Comment by jackyoh** [comment]
OK, 我來跑看看。

**Comment by jackyoh** [comment]
gradle 6.3 跑此 PR 的 branch 約花了 4 m 25s

gradle 5.6.4 跑 master branch 約花了 2 m 5s

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
will trace the flaky IT in #4488

**Pull request merged**
