### PR TITLE
#3945 [Manager] the gradle script should not change the yarn.lock file

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #3945)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
@chia7712 @jackyoh since this PR will nerve made into the test phrase (it will fail during the build step)
Is there an escape batch that I can get this in and save rest of our builds 😅

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
ping @konekoya 測試跑完了，如果沒問題就可以 mrege 到 master。我再來重 build ci 的 docker image

**Comment by saivirtue** [comment]
It's passed, let it merge!

**Comment by konekoya** [comment]
Thanks for the help guys!

**Pull request merged**
