### PR TITLE
#3674 add arguments to BasicTestPerformance#afterStoppingConnectors s…

### PR DESCRIPTION
**Pull request by chia7712**
…o as to not be viewed as test case

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #3674)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry assembly

**Comment by jackyoh** [comment]
afterStoppingConnectors 加參數的目的，我猜是要把 connectorInfos 和 topicInfos 暴露給 implement

**Comment by chia7712** [comment]
retry assembly

**Comment by chia7712** [comment]
@jackyoh retry assembly這個指令好像沒加到QA，可否幫忙處理一下，我人在外面不能用電腦QQ

**Comment by jackyoh** [comment]
> @jackyoh retry assembly這個指令好像沒加到QA，可否幫忙處理一下，我人在外面不能用電腦QQ

ok, 等等我來加上去

**Comment by jackyoh** [comment]
retry assembly

**Comment by jackyoh** [comment]
我已經把 retry assembly 加入到 QA 的 Expression 了

**Comment by jackyoh** [comment]
retry collieIT

**Comment by chia7712** [comment]
retry assembly

**Pull request merged**
