### PR TITLE
#4635 Upgrade all dependencies excluding hdfs

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4635)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by jackyoh** [comment]
很像 deps.dockerfile 的 libaio 套件也要升級。沒升級啟動 embeeded mysql 會有錯誤

**Comment by chia7712** [comment]
>很像 deps.dockerfile 的 libaio 套件也要升級。沒升級啟動 embeeded mysql 會有錯誤
 
我用現在的deps測試了一下，應該是套件升級後使用的mysql版本也跟著升級了，所以需要重新下載導致timeout和無法成功啟動的後續錯誤

我會趁著這幾天沒人送PR先手動更新deps讓它包含mysql然後再測試此PR

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry connector

**Comment by chia7712** [comment]
retry connector

**Comment by chia7712** [comment]
retry connector

**Comment by chia7712** [comment]
retry connector

**Comment by chia7712** [comment]
retry build

**Comment by chia7712** [comment]
will trace the DB in #4564

**Pull request merged**
