### PR TITLE
#789 streamApp list APIs will fail

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #789)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
fail only occure in ohara manager, no need to add tests
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
Could we have a test for this case?

**Comment by saivirtue** [comment]
> Could we have a test for this case?

For UT tests, I think `TestStreamRoute.scala` has covered most cases.
If we want to see the fail cases in manager, maybe we need to integrate the front-end e2e tests?

**Comment by chia7712** [comment]
I don’t dig in this issue. But is it hard to produce a request similar to https://github.com/akka/akka-http/issues/1216 on our UT?

**Comment by saivirtue** [comment]
> I don’t dig in this issue. But is it hard to produce a request similar to [akka/akka-http#1216](https://github.com/akka/akka-http/issues/1216) on our UT?

這個問題目前要

**Comment by chia7712** [comment]
@saivirtue ok

**Pull request merged**
