### PR TITLE
#476 update readme.md for bintray

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #476)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
這一個Issue會先針對master branch修改，主要的目的是加入：

1. 讓開發者可以將artifacts上傳到自己的JFrog Bintray內
2. 讓使用者可以了解如何引入dependencies

**Comment by vitojeng** [comment]
Hope ohara document will get better and better!

**Comment by saivirtue** [comment]
retry it

**Comment by saivirtue** [comment]
the error is not related, will merge this pr

**Pull request merged**
