### PR TITLE
#4460 ContainerClient#container(String) and ContainerClient#volume(St…

### PR DESCRIPTION
**Pull request by chia7712**
…ring) should return collection

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4460)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry collieIT

**Comment by jackyoh** [comment]
retry client

**Comment by jackyoh** [comment]
對了，我突然想到 ContainerInfo 的 case class 需要有 Volume 的資訊嗎？

**Comment by chia7712** [comment]
> 對了，我突然想到 ContainerInfo 的 case class 需要有 Volume 的資訊嗎？

等有需要的時候再綁在一起

**Comment by jackyoh** [comment]
OK, 了解。

**Pull request merged**
