### PR TITLE
#4041 Rename the root package from com.island.ohara to oharastream.ohara

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4041)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by vitojeng** [comment]
remind: **conf.py** also need to update, too.

**Comment by chia7712** [comment]
> remind: /docs/src/conf.py also need to update, too.

I don't see either "com" or "island" in the ```/docs/src/conf.py``. Do I miss something ?

**Comment by vitojeng** [comment]
> I don't see either "com" or "island" in the ```/docs/src/conf.py``. Do I miss something ?

I just think following lines should update, too:
```
copyright = u'2019, is-land Systems'
author = u'is-land Systems'
   :   :   :
latex_documents = [
    (master_doc, 'Ohara.tex', u'Ohara Documentation',
     u'is-land Systems', 'manual'),
]
```

**Comment by chia7712** [comment]
@vitojeng  what the replacement for "is-land Systems"? "oharastream"?

**Comment by vitojeng** [comment]
> "oharastream"?

ok

**Comment by saivirtue** [comment]
The changes were too huge to view...I think we should pass IT/E2E tests of QA for stability.
Also, please re-check the "hardcode" parts by searching the replacement text, thanks.
(ex: `TestConnectorRoute.scala` and `connectorApi.js`)

**Comment by chia7712** [comment]
> The changes were too huge to view...I think we should pass IT/E2E tests of QA for stability.

sure, boss :)

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
@saivirtue all pass !!!!

**Pull request merged**
