### PR TITLE
#2994 Update manager's development guideline

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2994)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
@saivirtue Any suggestions on things we're not including in the current docs but you wish were there?

**Comment by konekoya** [comment]
> we should better also remove old content in the docs

Yep, it's included in this PR :)

 and add a warning message for explaination at the top of User Guide.

Good idea! But do you mean in this file or [here](https://ohara.readthedocs.io/en/latest/user_guide.html)

**Comment by vitojeng** [comment]
> Good idea! But do you mean in this file or [here](https://ohara.readthedocs.io/en/latest/user_guide.html)

Oops! I confused with the user giude.
I mean we should remove the obsolete content of the user guide. XD

**Comment by saivirtue** [comment]
> @saivirtue Any suggestions on things we're not including in the current docs but you wish they were there?

Since I am quite a newbie in the front-end world, for me, they are almost problems of unfamiliar react, cypress...etc. 
Anyway, this guideline is clear for me to start an Ohara developer environment. :)

**Comment by konekoya** [comment]
Thanks for the review @vitojeng @saivirtue 💯

**Pull request merged**
