### PR TITLE
#1912 Support timestamp in metrics

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1912)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
What is means "startTime" for metrics? The time of generating the record in remote machine? Or the time to generate our BeanObject ?

**Comment by saivirtue** [comment]
> What is means "startTime" for metrics? The time of generating the record in remote machine? Or the time to generate our BeanObject ?

It should be the time of the record generated in remote machine. Let me add some document.

**Comment by chia7712** [comment]
> It should be the time of the record generated in remote machine.

Do all remote metrics objects have “startTime”? The metrics objects which are not generated by our APIs may have no startTime.

**Comment by saivirtue** [comment]
> Do all remote metrics objects have “startTime”? The metrics objects which are not generated by our APIs may have no startTime.

Do you mean like topic metrics? In that case, we use the BeanObject created time instead.
Since our metrics API allow user to define the "startTime" of each metric, Maybe we should remove the changeable "startTime" field to get the consistency?

**Comment by chia7712** [comment]
> Do you mean like topic metrics? In that case, we use the BeanObject created time instead.

It means the "startTime" is not the time of creating the metrics object, right? It causes the startTime from our metrics rest api is always the time of creating BeanObject. For example,

first call: GET /v0/topics/aaa
```json
{
  "startTime": 123
}
```

second call: GET /v0/topics/aaa
```json
{
  "startTime": 124
}
```

The "startTime" in both call should be identical since "startTime" is the time of "creating" metrics object. Personally, it is a critical bug to our rest apis.

> Since our metrics API allow user to define the "startTime" of each metric, Maybe we should remove the changeable "startTime" field to get the consistency?

The changeable startTime is useful in cloning object.

**Comment by saivirtue** [comment]
The "startTime" in both call should be identical since "startTime" is the time of "creating" metrics object. Personally, it is a critical bug to our rest apis.

Indeed. Let me find out if there were any native time of metric data could be used.

The changeable startTime is useful in cloning object.

OK

**Pull request merged**
