### PR TITLE
#525 Apply ohara Enum helper class to code base

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #525 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by saivirtue** [comment]
retry it

**Comment by saivirtue** [comment]
retry it

**Comment by chia7712** [comment]
You have to rebase PR since we had updated the rule of IT tests.

It is ok to merge this PR since the error is unconnected to this PR

**Comment by chia7712** [comment]
seems you have rebase the PR. Let me dig in what happen on k8s.

**Comment by chia7712** [comment]
The error is traced by #827 so I'm going to merge this PR.

**Comment by saivirtue** [comment]
> The error is traced by #827 so I'm going to merge this PR.

Thanks for the quick solving!

**Pull request merged**
