### PR TITLE
#5812 [Manager] Re-enable volume settings spec create workspace test

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist

- [x] [Review Contribution Guidelines](https://oharastream.github.io/en/docs/master/contributing/)
- [x] Add at least one reviewer (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add an assignee (of course, you are the assignee by default)
- [x] Do not set milestone, projects and labels (PR labels are added automatically by Jenkins)
- [x] Link to an issue
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (If the failed tests are unrelated to this PR, add a comment in the PR thread)

### CODE REVIEW

**Review by eechih — APPROVED** [review]

**Comment by konekoya** [comment]
retry manager-it

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by chia7712** [comment]
@konekoya 還是有問題嗎？在等這隻要做release了

**Comment by saivirtue** [comment]
retry manager-it

**Comment by konekoya** [comment]
> @konekoya 還是有問題嗎？在等這隻要做release了

I will try to get this in this morning. If the tests still fail, I will close the PR since this PR just re-enabled a skipped PR

**Comment by konekoya** [comment]
retry manager-e2e

**Pull request merged**
