### PR TITLE
#1332 Install required cypress dependencies in docker image

### PR DESCRIPTION
**Pull request by wu87988622**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by wu87988622** [comment]
retry manager

**Comment by chia7712** [comment]
@wu87988622 Are there any useless libraries after updating cypress???

**Comment by wu87988622** [comment]
> @ wu87988622更新cypress後是否有任何無用的庫？

I am checking, cypress for centos 7 Information is too old

**Comment by wu87988622** [comment]
retry manager

**Comment by chia7712** [comment]
+1

**Pull request merged**
