### PR TITLE
#2025 Change gradle command and update docs to use the new retry command

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2025)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
@chia7712 not sure if this error is on my end or yours... could you give a quick look?
https://builds.is-land.com.tw/job/PreCommit-OHARA/3958/console

**Comment by konekoya** [comment]
retry manager-api

**Comment by chia7712** [comment]
> not sure if this error is on my end or yours... could you give a quick look?

my bad :(

**Comment by chia7712** [comment]
retry manager-e2e

**Comment by chia7712** [comment]
retry manager-e2e

**Comment by chia7712** [comment]
seems all work well :)

**Comment by konekoya** [comment]
Oh wow, thanks you @chia7712 :)

**Pull request merged**
