### PR TITLE
#2812 remove the auto-completed cluster field from Topic APIs

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2812)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@wu87988622 @konekoya Seems Manager's UT still count on the autocomplete function ?

**Comment by chia7712** [comment]
retry agent

**Comment by chia7712** [comment]
retry k8sConfigurator

**Comment by wu87988622** [comment]
> @wu87988622 @konekoya Seems Manager's UT still count on the autocomplete function ?

I'll check this part.

**Comment by chia7712** [comment]
retry configurator

**Comment by chia7712** [comment]
@wu87988622 Could you help me to fix the APIs?

**Comment by saivirtue** [comment]
@chia7712 
Let me take over the conflict

**Comment by chia7712** [comment]
@saivirtue

It is not conflict. The root cause is most tests written before this PR do not assign the broker cluster key. Defining the broker cluster key explicitly is able to fix all tests.

Also, thanks for taking over this PR :)

**Comment by saivirtue** [comment]
> The root cause is most tests written before this PR do not assign the broker cluster key.
> 
> Also, thanks for taking over this PR :)

No problem :)

My point is, should we throw an exception if user input a wrong brokerClusterKey in TopicAPI ?
For example,

``
{
  "brokerClusterKey" : {
    "name" : "fake",
    "group" : "fake"
  }
}

**Comment by chia7712** [comment]
> input a wrong brokerClusterKey

Yep, we should reject the request referring nonexistent key. Quick failure is always good stuff.

**Comment by saivirtue** [comment]
retry sshConnector

**Comment by saivirtue** [comment]
retry sshConnector

**Comment by chia7712** [comment]
retry sshConnector

**Comment by chia7712** [comment]
the IT error is traced by #3013

**Comment by chia7712** [comment]
Let me merge it now :)

**Pull request merged**
