### PR TITLE
#513 Update spotless from 3.15.0 to 3.20.0

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #513)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
      no test :(
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
the checkstyle works well. Seems the stale jars are unstable...

**Comment by chia7712** [comment]
the license error is traced by #515

**Comment by chia7712** [comment]
> 是因為版本更新, 而造成許多的 code reformat?

yep

**Comment by vitojeng** [comment]
會不會以後升級都被 reformat ... XD

**Comment by chia7712** [comment]
> 會不會以後升級都被 reformat ... XD

搞不好XDDD 沒事別亂升級就好..

**Comment by chia7712** [comment]
TestK8sClusterCollie is unrelated to this PR.

**Pull request merged**
