### PR TITLE
#1549 The default acks of Producer should be 1 than zero

### LINKED ISSUE #1549: The default acks of Producer should be 1 than zero
```java
  class Builder<Key, Value> implements com.island.ohara.common.Builder<Producer<Key, Value>> {
    private short numberOfAcks = 0;
```

The default acks is zero and it means that we don't want the acknowledgement from any broker. It does not make sense if we want to expose this Producer client to normal developers.

[code link](https://github.com/oharastream/ohara/blob/master/ohara-kafka/src/main/java/com/island/ohara/kafka/Producer.java#L59)

### PR DESCRIPTION
**Pull request by dc-tw**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1549)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@dc-tw 請勿把預設的checklist刪掉~

**Comment by chia7712** [comment]
@dc-tw 因為某個模組測試有發生錯誤，有時候這只是因為我們的伺服器太忙而導致，此時可以透過QA命令來使其重試，命令細節可以參考[docs](https://oharastream.readthedocs.io/en/latest/contributing.html)

**Comment by chia7712** [comment]
retry configurator

**Comment by dc-tw** [comment]
了解，我以為寫的簡短點會好些

**Comment by chia7712** [comment]
@dc-tw 另外PR的標題開頭的編號應該要與issue number一樣。例如此PR對應的issue number是#1549，因此標題應該是#1549 The default acks of Producer should be 1 than zero

**Comment by chia7712** [comment]
retry configurator

**Comment by chia7712** [comment]
retry configurator

**Comment by chia7712** [comment]
retry configurator

**Comment by chia7712** [comment]
retry configurator

**Comment by konekoya** [comment]
retry configurator

**Comment by dc-tw** [comment]
@chia7712  請問我是重設什麼參數嗎?
還是那是call 其他自動化檢測的指令

**Comment by chia7712** [comment]
@dc-tw please rebase your PR

**Comment by dc-tw** [comment]
retry

**Pull request merged**
