### PR TITLE
#1363 Replace 0.5-SNAPSHOT with 0.6-SNAPSHOT in ohara codebase

### PR DESCRIPTION
**Pull request by eechih**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1363 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by eechih** [comment]
@chia7712 @saivirtue @jackyoh Pinging all Jenkins maintainers!

Please update Jenkins tasks to use 0.6-SNAPSHOT tag instead of 0.5-SNAPSHOT.

Thanks!

**Comment by chia7712** [comment]
> Please update Jenkins tasks to use 0.6-SNAPSHOT tag instead of 0.5-SNAPSHOT.

The version in QA is based on root/gradle.properties. Hence, we don't need to update any bit of QA.

**Comment by eechih** [comment]
> The version in QA is based on root/gradle.properties.

@chia7712  請問 QA 所指的範圍，是否包含 deploy to QAII 的項目？

**Comment by chia7712** [comment]
QA is built by PreCommit-Ohara. Deploy-Ohara needs to update manually.

**Comment by eechih** [comment]
ping @saivirtue 

Please update Jenkins task (Deploy-Ohara) to use 0.6-SNAPSHOT tag instead of 0.5-SNAPSHOT.

Thanks!

**Pull request merged**
