### PR TITLE
OHARA-1411 add mysql image

### PR DESCRIPTION
**Pull request by chia7712**

### CODE REVIEW

**Comment by chia7712** [comment]
retry connector

**Comment by vitojeng** [comment]
@chia7712 Does there have any pre-prepared table and records ?

**Comment by chia7712** [comment]
> Does there have any pre-prepared table and records ?

I will fire a jira for this. Let me complete all tasks first....

**Comment by chia7712** [comment]
retry connector

**Comment by chia7712** [comment]
The failed test is unrelated to this PR. Will merge this.

**Pull request merged**
