### PR TITLE
#2731 Stream APIs should honor cluster key

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2731)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
retry it

**Comment by chia7712** [comment]
the error is caused by #2682

**Comment by saivirtue** [comment]
> the error is caused by #2682

How so? Do the IT tests use illegal chars for object key?

**Comment by chia7712** [comment]
> How so? Do the IT tests use illegal chars for object key?

upper case :(

but, there is other error in our IT. let me dig in it :)

**Comment by saivirtue** [comment]
> but, there is other error in our IT. let me dig in it :)

OK. For more reliable PR, I will wait for the problem resolved and retry the it tests.

**Comment by chia7712** [comment]
retry it

**Comment by chia7712** [comment]
retry it

**Comment by chia7712** [comment]
retry it

**Comment by chia7712** [comment]
retry otherIT

**Comment by saivirtue** [comment]
The failed tests are traced in #2818 and #2821, will merge this PR later

**Pull request merged**
