### PR TITLE
OHARA-1392 Enable jenkins to run ohara-manager only when PR …

### PR DESCRIPTION
**Pull request by chia7712**
這個PR用來測試如果變更只集中在ohara-manager的話，QA預設只針對ohara-manager

### CODE REVIEW

**Comment by chia7712** [comment]
retry common

**Comment by konekoya** [comment]
I'm good with this, thanks 👍

**Comment by chia7712** [comment]
> I'm good with this, thanks

Thanks for reviews!

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
retry manager

**Comment by chia7712** [comment]
retry manager

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
seems our jenkins love this PR. Will close this PR.

**Pull request closed without merging**
