### PR TITLE
 #808 support k8s in stream router

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #808)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
**Since k8s dose not implement mock object yet (#729), will add it tests in #900**
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
Do you want to integrate collie and crane? @jackyoh What is the plan? 

We have a shabondi and a bunch of improvement for our docker manager (both of collie and crane), and they are going to be added to our ohara. If we fail to integrate them, all of them will be hard to sync with all improvement. Also, it is really really really weird if a function works only on part of ohara services.

**Comment by saivirtue** [comment]
> Do you want to integrate collie and crane? 

for the big picture, +1
Crane and Collie have much similar codes, and we should integrate them for more features coming.
But, collie has some structure (ClusterCollie) for Big Three services (zk, bk, wk) and it is hard to integrate  stream in them.
at any rate, I think we can start refactor this part before logic becoming complex.
create an issue to trace this
- [ ] Refactor crane to collie #904

**Comment by jackyoh** [comment]
> Do you want to integrate collie and crane? @jackyoh What is the plan?
> 
> We have a shabondi and a bunch of improvement for our docker manager (both of collie and crane), and they are going to be added to our ohara. If we fail to integrate them, all of them will be hard to sync with all improvement. Also, it is really really really weird if a function works only on part of ohara services.

我這邊的規劃如下：
1. 把 ssh 和 k8s 相同邏輯放在 ContainerCollier 的 class 下面, 再由 ssh 和 k8s 的實做來繼承

2. 之後實做 streamapp 或是 shabondi 的 collie 有相同邏輯的話, 就放在 ContainerCollier

3. 把 docker client 和 k8s client 做一個 trait, 有一個相同的界面. 這樣回傳值才會有相同的資料格式

4. 未來實做 streamapp, shabondi 或是其他元件都不需要知道是使用 docker 或是 k8s 的 client, 只要呼叫到界面就可以了.

**Comment by saivirtue** [comment]
> 我這邊的規劃如下： (略)

與@jackyoh 討論後，stream cluster這邊的邏輯重構會以#905 為主，整合到`ContainerCollie`，#904 的內容我這邊會稍作修改

**Pull request merged**
