### PR TITLE
#1394 Fix frontend vulnerabilities

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1394)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@konekoya Is you scared of Github robot?

**Comment by konekoya** [comment]
> @konekoya Is you scared of Github robot?

Ha, definitely not. I just wanted to make sure where do these vulnerabilities come from and fix them manually :)

**Comment by konekoya** [comment]
retry manager

**Comment by vitojeng** [comment]
> > @konekoya Is you scared of Github robot?
> 
> Ha, definitely not. I just wanted to make sure where do these vulnerabilities come from and fix them manually :)

Github robot also needs to follow the rule in ohara: create an issue before a PR.  😆

**Comment by chia7712** [comment]
retry manager-ut

**Comment by chia7712** [comment]
retry manager-ut

**Comment by chia7712** [comment]
@konekoya Could you focus push this PR to reset all status?

**Comment by konekoya** [comment]
> @konekoya Could you focus push this PR to reset all status?

Updated :)

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
retry manager-it

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager-it

**Comment by konekoya** [comment]
retry manager-it

**Comment by wu87988622** [comment]
retry manager-it

**Comment by konekoya** [comment]
Thanks for the review @wu87988622!

**Comment by konekoya** [comment]
Fail build is not related, merging this PR

**Pull request merged**
