### PR TITLE
#5163 remove docs folder

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #5163)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by vitojeng** [comment]
@chia7712 /docs/testcase/*.md 不在這次的範圍裡, 需要暫時留下來

**Comment by chia7712** [comment]
> /docs/testcase/*.md 不在這次的範圍裡, 需要暫時留下來

#5282?

那等你ok後我再來完成這隻pr

**Comment by vitojeng** [comment]
@chia7712  
己經完成  test case migration. https://github.com/oharastream/ohara-docs/pull/40

**Comment by vitojeng** [comment]
@chia7712  
**.readthedocs.yml** file need remove, too.

**Pull request merged**
