### PR TITLE
#2438 remove stale fields for WorkerClusterInfo

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2438)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager-api

**Comment by konekoya** [comment]
@saivirtue Please help resolve the merge conflict

**Comment by saivirtue** [comment]
> @saivirtue Please help resolve the merge conflict

Done 😎

**Comment by saivirtue** [comment]
retry configurator

**Comment by saivirtue** [comment]
It seems still have some problem:
```
createWorker.Worker API createWorker (from Worker API)

錯誤訊息
expected undefined to be a string
堆疊追蹤
AssertionError: expected undefined to be a string
    at getRet (http://localhost:51465/__cypress/runner/cypress_runner.js:71895:16)
    at tryCatcher (http://localhost:51465/__cypress/runner/cypress_runner.js:118962:23)
    at Function.Promise.attempt.Promise.try (http://localhost:51465/__cypress/runner/cypress_runner.js:116237:29)
    at Context.thenFn (http://localhost:51465/__cypress/runner/cypress_runner.js:71909:23)
    at Context.then (http://localhost:51465/__cypress/runner/cypress_runner.js:72229:21)
    at Context.<anonymous> (http://localhost:51465/__cypress/runner/cypress_runner.js:80256:21)
    at http://localhost:51465/__cypress/runner/cypress_runner.js:79783:33
    at tryCatcher (http://localhost:51465/__cypress/runner/cypress_runner.js:118962:23)
    at Promise._settlePromiseFromHandler (http://localhost:51465/__cypress/runner/cypress_runner.js:116898:31)
    at Promise._settlePromise (http://localhost:51465/__cypress/runner/cypress_runner.js:116955:18)
    at Promise._settlePromiseCtx (http://localhost:51465/__cypress/runner/cypress_runner.js:116992:10)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:51465/__cypress/runner/cypress_runner.js:113692:12)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:51465/__cypress/runner/cypress_runner.js:113697:10)
    at Async.drainQueues (http://localhost:51465/__cypress/runner/cypress_runner.js:113571:14)
    at <anonymous>
```

**Comment by konekoya** [comment]
> It seems still have some problem: (/cc @konekoya )

Hmm, it should have been resolved... I will give it a look as soon as i can

**Comment by konekoya** [comment]
> It seems still have some problem: (/cc @konekoya )

We missed changing an assertion in one of our worker API tests. I have pushed the update, the test should be all passed this time :)

**Comment by saivirtue** [comment]
Thanks @konekoya !
I will merge this PR later.

**Pull request merged**
