### PR TITLE
#3842 Integrate TopicAdmin with BrokerClient

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #3842)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by jackyoh** [comment]
BrokerClient 改變成 TopicAdmin，是因為 Kafka 升版的原因嗎？

**Comment by chia7712** [comment]
> BrokerClient 改變成 TopicAdmin，是因為 Kafka 升版的原因嗎？

主要是把scala和java版本合併，然後保留TopicAdmin這個名字

**Comment by jackyoh** [comment]
> 主要是把scala和java版本合併，然後保留TopicAdmin這個名字

ok, 了解。Thank you

**Comment by chia7712** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Pull request merged**
