### PR TITLE
#5106 Fix wrong yarn version in docker files

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #5106)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
So this causes the ```install``` when running QA?

**Comment by konekoya** [comment]
> So this causes the install when running QA?

Nope, this edit only affects the docker files, I mistyped the yarn version in the previous PR...

**Comment by chia7712** [comment]
https://builds.is-land.com.tw/job/PreCommit-OHARA/10606/artifact/checks/build_image.log

```
Step 18/31 : RUN npm install -g yarn@1.12.4
 ---> Running in 2e32f9c36adc
[91mnpm ERR! code ETARGET
[0m[91mnpm ERR! notarget[0m[91m No matching version found for yarn@1.12.4.
[0m[91mnpm ERR![0m[91m [0m[91mnotarget In most cases you or one of your dependencies are requesting
npm[0m[91m ERR! [0m[91mnotarget a package version that doesn't exist.
[0m[91m
npm ERR![0m[91m A complete log of this run can be found in:
npm[0m[91m ERR![0m[91m     /root/.npm/_logs/2020-06-09T04_06_24_980Z-debug.log
[0mRemoving intermediate container 2e32f9c36adc

ERROR: for manager  (<Service: manager>, "The command '/bin/sh -c npm install -g yarn@1.12.4' returned a non-zero code: 1")
Service 'manager' failed to build: The command '/bin/sh -c npm install -g yarn@1.12.4' returned a non-zero code: 1
```

Is above error related to this PR?

**Comment by konekoya** [comment]
> Is above error related to this PR?

Yes. thought it won't affect the current QA...

**Comment by konekoya** [comment]
> Is above error related to this PR?

@chia7712 and @jackyoh Could you guys try rebuilding image again. This should be resolved by now. Sorry about this 😅

**Comment by jackyoh** [comment]
OK, 等等來重 build 一次。Thank you.

**Pull request merged**
