### PR TITLE
#2156 have file url end with jar name so as to make downloaded file h…

### PR DESCRIPTION
**Pull request by chia7712**
…ave proper name

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2156)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry it

**Comment by saivirtue** [comment]
It seems we need to refactor here also:
```
override def route(implicit executionContext: ExecutionContext): Route =
      pathPrefix(DOWNLOAD_FILE_PREFIX_PATH / Segment) { name =>
        parameter(GROUP_KEY ?) { groupOption =>
          val key = ObjectKey.of(groupOption.getOrElse(FileInfoApi.GROUP_DEFAULT), name)
          if (!isAcceptedFilename(name))
            complete(
              StatusCodes.NotFound -> s"$name is illegal. Accepted extensions are ${acceptedExtensions.mkString(",")}")
          // TODO: how to use future in getFromFile???
          else getFromFile(Await.result(toFile(key), 30 seconds))
        }

      }
```

**Comment by chia7712** [comment]
retry it

**Comment by chia7712** [comment]
retry it

**Comment by chia7712** [comment]
retry it

**Comment by chia7712** [comment]
retry it

**Comment by chia7712** [comment]
unrelated error

**Pull request merged**
