### PR TITLE
#4791 [Bug] Trigger the workspace to restart, the progress bar does n…

### PR DESCRIPTION
**Pull request by wu87988622**
…ot appear immediately

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4791 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
The percentage could be wrong in some occasions though...

**Comment by wu87988622** [comment]
> The percentage could be wrong in some occasions though...

你是指會超過100嗎？

**Comment by chia7712** [comment]
這隻PR的狀況如何？嗷嗷待哺等這個修復

**Comment by konekoya** [comment]
> 你是指會超過100嗎？

Nevermind, let's merge this first for @chia7712

**Comment by wu87988622** [comment]
> > 你是指會超過100嗎？
> 
> Nevermind, let's merge this first for @chia7712

ok

**Pull request merged**
