### PR TITLE
#4705 Integrate scala library into stream image

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4705)
local test :)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by jackyoh** [comment]
stream.dockerfile 的檔案有需要設定 scala library 的 CLASSPATH 嗎？

**Comment by chia7712** [comment]
> stream.dockerfile 的檔案有需要設定 scala library 的 CLASSPATH 嗎？

不用，我們都是透過distributions去部署libraries，所以只要確保說scala libararies有被stream assembly包含就可以了

**Comment by jackyoh** [comment]
> 不用，我們都是透過distributions去部署libraries，所以只要確保說scala libararies有被stream assembly包含就可以了

了解， Thank you.
我又另外想到ㄧ個問題 ohara 的 stream 應該只能規定使用某個版本的 scala 是否需要在文件上註明一下。

**Comment by chia7712** [comment]
> 我又另外想到ㄧ個問題 ohara 的 stream 應該只能規定使用某個版本的 scala 是否需要在文件上註明一下。

https://ohara.readthedocs.io/en/latest/how_to_build.html#build

我們已經有標上scala版本了

**Comment by jackyoh** [comment]
> 我們已經有標上scala版本了

有看到了， Thank you.

**Comment by chia7712** [comment]
the flaky zk is traced by #3368

**Pull request merged**
