### PR TITLE
#3807 Fix incorrect restful api link

### PR DESCRIPTION
**Pull request by vitojeng**
required by #3807

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by vitojeng** [comment]
@chia7712 
I would like to add a testing for valid apiUrl in this PR.

**Comment by vitojeng** [comment]
retry

**Comment by jackyoh** [comment]
程式碼很像沒有 rebase

https://github.com/vitojeng/ohara/blob/fix-rest-url/gradle.properties

**Comment by vitojeng** [comment]
retry connectorIT

**Comment by vitojeng** [comment]
retry configurator

**Comment by jackyoh** [comment]
retry configurator

**Comment by jackyoh** [comment]
retry configurator

**Comment by vitojeng** [comment]
retry configurator

**Pull request merged**
