### PR TITLE
#5385 [Manager] Prevent users to use the unstable workspace

### PR DESCRIPTION
**Pull request by eechih**
### Checklist

- [x] [Review Contribution Guidelines](https://oharastream.github.io/en/docs/master/contributing/)
- [x] Add at least one reviewer (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add an assignee (of course, you are the assignee by default)
- [x] Do not set milestone, projects and labels (PR labels are added automatically by Jenkins)
- [x] Link to an issue #5385 
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (If the failed tests are unrelated to this PR, add a comment in the PR thread)

### CODE REVIEW

**Comment by eechih** [comment]
retry manager-it

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by eechih** [comment]
> could we add a test for WorkspaceList?

sure

**Comment by eechih** [comment]
@saivirtue I've add a test for `workspace list`. Please review again, thanks :)

**Pull request merged**
