### PR TITLE
#2970 the length of container host name is too long

### PR DESCRIPTION
**Pull request by chia7712**
backport to 0.8 (related to #2970)

### CODE REVIEW

**Comment by chia7712** [comment]
retry sshConfigurator

**Comment by chia7712** [comment]
retry sshConfigurator

**Comment by chia7712** [comment]
retry k8sConfigurator

**Comment by jackyoh** [comment]
retry sshConfigurator

**Comment by chia7712** [comment]
retry sshConfigurator

**Comment by chia7712** [comment]
@konekoya I'm going to close this PR since this bug is not critical. Also, this change is too big to be a hot fix.

**Pull request closed without merging**
