### PR TITLE
#3270 Set the version definition to READONLY in zookeeper, broker and…

### PR DESCRIPTION
**Pull request by chia7712**
… worker

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #3270)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by jackyoh** [comment]
retry sshConfigurator

**Comment by jackyoh** [comment]
這個 PR 應該就是下午所說的 image name 都改成唯讀。

**Comment by chia7712** [comment]
> 這個 PR 應該就是下午所說的 image name 都改成唯讀。

U are right :)

**Comment by chia7712** [comment]
retry sshConfigurator

**Pull request merged**
