### PR TITLE
OHARA-1388 Remove monitoring from main nav 

### PR DESCRIPTION
**Pull request by konekoya**
- Removed monitoring from main navigation, we're not going to include this feature in v0.2
- Fixed failing e2e and unit tests

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry connector

**Comment by konekoya** [comment]
retry manager

**Comment by jackyoh** [comment]
retry configurator

**Comment by konekoya** [comment]
Manager build passed, merging this PR

**Pull request merged**
