### PR TITLE
#5092 [Manager] Hide selected items in the file selector

### PR DESCRIPTION
**Pull request by eechih**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #5092 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by eechih** [comment]
我認為這個 PR 不適合 merge 到 0.10.0，因為 node selector 也需要有相對應的調整，不然 UI 會出現不一致的行為。

@oharastream/developer 大家有何看法？

**Comment by konekoya** [comment]
> 大家有何看法？

I would agree on moving this to 0.11 if it does require making a lot more changes and it's not a crucial bug

**Comment by saivirtue** [comment]
agree with move to 0.11

**Comment by eechih** [comment]
OK, I close this PR since will be resolved to next version.

**Pull request closed without merging**
