### PR TITLE
#102 CI Status on Readme

### PR DESCRIPTION
**Pull request by Wei-1**
After https been added to Jenkins, we can visualize the build status for users to check.

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #102)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by Wei-1** [comment]
I don't seem to have authentication to assign reviewers and some items in the list don't seem applicable so I will leave it blank.
Please check if any modification needs to be done.

**Comment by chia7712** [comment]
@Wei-1 Thanks for this PR. The link you used is not up-to-date build status. It is "Pre"Commit that show the build status for Pull Request. We haven't set up the build for each merge :(

However, the badges has attracted me. I will attach a link to up-to-date build status ASAP :)

**Comment by Wei-1** [comment]
You are correct, showing release status will be better.
@chia7712, That's awesome. I will close this PR for now.

**Comment by chia7712** [comment]
> That's awesome. I will close this PR for now.

Could you wait a minute. I love this PR :)

**Comment by chia7712** [comment]
@Wei-1  https://builds.is-land.com.tw/buildStatus/icon?job=PostCommit-OHARA

**Comment by Wei-1** [comment]
> @Wei-1 https://builds.is-land.com.tw/buildStatus/icon?job=PostCommit-OHARA

Modified based on the link!

**Comment by chia7712** [comment]
@Wei-1 Thanks for the contribution :)

**Comment by vitojeng** [comment]
@Wei-1 Awesome!

**Comment by konekoya** [comment]
Oh wow! This is really awesome. Thanks, @Wei-1 💯 🥇

**Comment by Wei-1** [comment]
I mean... it is just a badge though...

**Comment by chia7712** [comment]
They all are exciting to talk with human.

**Pull request merged**
