### PR TITLE
#2262 Docs: remove hard code version value

### PR DESCRIPTION
**Pull request by vitojeng**
required by #2262

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
這個 PR 先不要合併，借我測試 QA

**Comment by wu87988622** [comment]
> 這個 PR 先不要合併，借我測試 QA

ok

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
retry

**Comment by jackyoh** [comment]
這是我的烏龍，測試完成可以 mrege 這個 PR 了

**Comment by vitojeng** [comment]
Thanks @wu87988622 & @jackyoh !!

**Pull request merged**
