### PR TITLE
#464 Expose the thread pool used by async function

### PR DESCRIPTION
**Pull request by chia7712**
required by #464

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #464)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
This is a huge PR since all async function are changed....

**Comment by vitojeng** [comment]
Thanks @chia7712 for the huge improvement!

> This is a huge PR since all async function are changed....

Yep...does there has any way to split into several parts?

I realize that the huge change is due to base class api changed.
But I would suggest making this PR change more small and smooth step.

**Comment by saivirtue** [comment]
Oh...I need some time to review this PR totally
Let me finish the release work and back to this :)

**Comment by vitojeng** [comment]
> But I would suggest making this PR more small and smooth step to understanding the whole changed.

@chia7712 Just a discussion. Not need to update this PR. 🙂

**Comment by chia7712** [comment]
bq. does there has any way to split into several parts?

This issue is about dead lock. I tried to fix "only" the bug however it would make a weird code changes. That is side effect from our code infra (and it is my fault :(  )

**Comment by vitojeng** [comment]
> This issue is about dead lock.

Oh...I got it.
If this is about a bug fix, not an improvement. I totally agree with you!

**Comment by chia7712** [comment]
retry it

**Comment by konekoya** [comment]
Awesome, thanks for fixing this @chia7712!

**Pull request merged**
