### PR TITLE
#2802 remove stale group, name, numberOfPartitions, numberOfReplicati…

### PR DESCRIPTION
**Pull request by chia7712**
…ons and tags from Topic APIs

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2802)
cleanup code :)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry manager-ut

**Comment by chia7712** [comment]
retry sshConfigurator

**Comment by chia7712** [comment]
@wu87988622 Could you help me to fix the ut?

**Comment by wu87988622** [comment]
> @wu87988622 Could you help me to fix the ut?

ok

**Comment by chia7712** [comment]
@wu87988622 Is it time to go in?

**Comment by wu87988622** [comment]
> @wu87988622 Is it time to go in?

sure

**Pull request merged**
