### PR TITLE
#3770 the sinceSeconds does not work since we calculate the duration by incorrect unit

### PR DESCRIPTION
**Pull request by chia7712**
backport to 0.9.x (related to #3770)

### CODE REVIEW

**Comment by jackyoh** [comment]
程式碼很像發生衝突了

**Comment by chia7712** [comment]
> 程式碼很像發生衝突了

貼太快了 QQ

邊測試UI邊回覆留言邊敲代碼，不小心就手殘了

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
unrelated error

**Pull request merged**
