### PR TITLE
#2471 Update manager's dependencies

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2471)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
@chia7712 I've retried this two times and the unit test actually passed in the Jenkins job but failed in the GitHub check. Do you have any idea 😅

**Comment by chia7712** [comment]
the form of report is changed. It has the header "<?xml version="1.0" encoding="UTF-8"?>" now. Is the changed caused by this PR? If so, I can update our jenkins to handle it :)

**Comment by konekoya** [comment]
> the form of report is changed. It has the header "" now. Is the changed caused by this PR? If so, I can update our jenkins to handle it :)

Yes, the changed is caused by this PR. Sorry, I didn't notice the report has changed 😅

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by chia7712** [comment]
> Yes, the changed is caused by this PR. Sorry, I didn't notice the report has changed

I have updated the jenkins, and you have to retry to enjoy the new QA :)

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-ut

**Comment by konekoya** [comment]
@chia7712 I've updated the PR, could you give it a look again?

https://builds.is-land.com.tw/job/PreCommit-OHARA/4976/artifact/ohara/ohara-manager/test-reports/

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by chia7712** [comment]
retry manager-ut

**Comment by chia7712** [comment]
retry manager-ut

**Comment by chia7712** [comment]
@konekoya all work well now. I feel it is time to merge PR

**Comment by konekoya** [comment]
@chia7712 Thank you so much for this! Yep, since everything is passing. Let's merge it 💯

**Pull request merged**
