### PR TITLE
#4391 Fix cypress is not able to be downloaded issue

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4391)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
@chia7712 please don't merge this PR before the e2e test passed as I have bump the cypress version and that could potentially break our tests...

**Comment by chia7712** [comment]
retry manager-api

**Comment by konekoya** [comment]
retry

**Comment by konekoya** [comment]
retry manager-api

**Comment by konekoya** [comment]
retry manager-api

**Pull request merged**
