### PR TITLE
#1620 Fix flaky Workers.fetchWorker and Workers.createWorker

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1620)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@wu87988622 any suggestions?

**Comment by wu87988622** [comment]
> @wu87988622 any suggestions?

This api test is fix in #1540

**Comment by chia7712** [comment]
> This api test is fix in #1540

ok. But, please try to quickly fix the small the obvious error via independent PR than including it in a big and slow stuff ... We all hate to see a always failed QA in each PR.

**Comment by wu87988622** [comment]
> > This api test is fix in #1540
> 
> ok. But, please try to quickly fix the small and obvious error via independent PR than including it in a big and slow stuff ... We all hate to see a always failed QA in each PR.

ok.
I will be more careful next time.

**Pull request closed without merging**
