### PR TITLE
#2434 Update version of 0.7 branch to 0.7.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by wu87988622**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2434 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
the error is caused by that there is no image with tag "0.7.1-SNAPSHOT", and the error can't burn out our project :)

**Comment by wu87988622** [comment]
> the error is caused by that there is no image with tag "0.7.1-SNAPSHOT", and the error can't burn out our project :)

In labels ohara-robot create the new v0.7.1 is fine?

**Comment by chia7712** [comment]
> In labels ohara-robot create the new v0.7.1 is fine?

absolutely fine! and you have to redefine the label for consistency (it has incorrect color now)

**Comment by wu87988622** [comment]
> > In labels ohara-robot create the new v0.7.1 is fine?
> 
> absolutely fine! and you have to redefine the label for consistency (it has incorrect color now)

Ok Thanks you~

**Pull request merged**
