### PR TITLE
#2695 [Manager] Assign broker cluster name to stream application

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2695)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by jackyoh** [comment]
我在 k8s 的整合測試環境上看到有以下的錯誤：
```
WORKER_JAR_URLS is required since you have set the jarInfos:[]
```
不太確定是否有漏塞到設定造成 container error 的問題

**Comment by chia7712** [comment]
> WORKER_JAR_URLS is required since you have set the jarInfos:[]

this was a bug. It is fixed #2687. Maybe our images is out-of-date :(

**Comment by konekoya** [comment]
retry manager-e2e

**Pull request merged**
