### PR TITLE
#2746 [Manager] Update unit tests packages

### PR DESCRIPTION
**Pull request by wu87988622**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2746 )
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by wu87988622** [comment]
@konekoya 
we update testing-library/cypress to 5.0.1, any cypress test getXXXX change to findXXXX
ex.getByText -> findByText

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
> we update testing-library/cypress to 5.0.1, any cypress test getXXXX change to findXXXX
ex.getByText -> findByText

Looks like they just updated this a few days ago

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
@wu87988622 The release date is approaching, If there are many changes required (lots of failing tests due to this version bump) to be done to get this PR merged. I think we can postpone this for the next release for good.

**Comment by wu87988622** [comment]
retry manager-e2e

**Comment by wu87988622** [comment]
> @wu87988622 The release date is approaching, If there are many changes required (lots of failing tests due to this version bump) to be done before we can get this PR merged. I think we can postpone this for the next release for good.

ok thanks.

**Pull request closed without merging**
