### PR TITLE
#1087 Cannot run streamApp normally in pipeline

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1087)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
Could you share the root cause? Incorrect path?

**Comment by saivirtue** [comment]
> Could you share the root cause? Incorrect path?

See issue #1087, I have add the root cause in there

**Comment by chia7712** [comment]
> This is due to the file copy function CommonUtils.copyURLToFile will check the destination file should not be exist, but streamApp will create a temp file first...

We should add a variety (or a flag) to copyURLToFile() to enable it to overwrite an existent file. That can help other people to handle the issue like this one.

**Comment by saivirtue** [comment]
> > This is due to the file copy function CommonUtils.copyURLToFile will check the destination file should not be exist, but streamApp will create a temp file first...
> 
> We should add a variety (or a flag) to copyURLToFile() to enable it to overwrite an existent file. That can help other people to handle the issue like this one.

Well, the overwrite case  is rare, I think we can change the parameters to ((URL source, **String destinationFileName**, int connectionTimeout, int readTimeout) ; And add a small reminder in javadoc
how's that sound?

**Comment by chia7712** [comment]
Another way is to add an new helper method which can download URL to a temporary file directly.
For example:

public static File downloadUrl(URL url)

The method iron out the temporary file issue.

**Comment by saivirtue** [comment]
> public static File downloadUrl(URL url)

sounds great +1. file another issue instead.
BTW, this pr will be merge soon if there was no any other issue.

**Comment by chia7712** [comment]
It would be better to have a test for this case...

**Comment by saivirtue** [comment]
> It would be better to have a test for this case...

We have a streamApp test in `it` module, but there seems have some weird response of containerStatus from K8sClient (already tell to @jackyoh , reference issue is in #1091 ) ; this situation cause streamApp it test could run normally but actually is fail (CrashLoopBackOff)

**Comment by chia7712** [comment]
We can’t verify the startup for s streamapp by UT?

**Comment by saivirtue** [comment]
> We can’t verify the startup for s streamapp by UT?

as #1091 describe, streamApp will get `Running` even if the actual container(s) are `CrashLoopBackOff`

**Comment by chia7712** [comment]
My point is - could we reproduce this bug in our testing code?Could we mock the incorrect information in UT?

**Comment by saivirtue** [comment]
這邊的狀況是，錯誤的是"K8s 內Pod的containers"，而不是"Pod本身"；我們透過K8sClient互動的物件都是"Pod"
UT上無法mock K8s內部的狀態

**Comment by saivirtue** [comment]
> we can assume that streamapp is able to download file

OK, now I got your point.
first, I can check the file download part, and this test case is my mistake :( , see issue #1101
but for this issue root cause, I think we can separate two different view :
1. from container view : root cause is download file fail
2. from ohara manager view : root cause is k8s client could not response correct status of container

In the second view, I think there is no way to add unit test, at least for now.

**Comment by chia7712** [comment]
> from ohara manager view : root cause is k8s client could not response correct status of container

其實也可以做UT。因為k8s client是透過restful溝通，我們可以透過Akka fake一個k8s server並回傳#1091你列舉的json response，然後看看k8s client是否有轉成我們預期的結果

**Pull request merged**
