### PR TITLE
Update .gitignore with a space

### PR DESCRIPTION
**Pull request by dc-tw**
### Checklist
- [ ] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [ ] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [ ] Add Assignees (of course, you are the assignee by default!)
- [ ] DON'T set a Milestone
- [ ] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [ ] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@dc-tw 這個QA錯誤跟你的PR無關。不過你的PR有幾個地方需要調整：
1. PR的抬頭格式為 #issue_number issue_title
這部分可以參考一下其他PR

2. 我不確定這隻PR是要修復什麼，因為好像也沒有對應的issue

**Comment by dc-tw** [comment]
@chia7712 了解,我剛剛這個是為了測試是否可以pr
我應該改為#1574 The default acks of Producer should be 1 than zero

我後來我實際把numberOfAcks預設為1之後
要PR回oharastream的repo時
無法產生pr, 請問是因為前個pr沒有被拒絕或接受嗎?

**Comment by chia7712** [comment]
> 要PR回oharastream的repo時

抱歉 我沒有看懂這句話。

可否把你敲的指令貼上來？

**Comment by dc-tw** [comment]
並不是指令
我已經git push到我的repo
然後按github介面的new pull request
因為改動了code, 所以應有create pull request, 但沒有

**Comment by chia7712** [comment]
一隻branch一隻PR，你在該branch提交的新commit會反映在PR上面。所以你不用再開PR。

**Pull request closed without merging**
