### PR TITLE
Provide branch name in gradle.properties

### PR DESCRIPTION
**Pull request by vitojeng**
required by #1867 

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by vitojeng** [comment]
retry

**Comment by chia7712** [comment]
@vitojeng the branch name consisting of only number will confuse git that it tries to make the code base checkout to a "commit hash" than "branch". Could you file another PR with suitable branch name?

**Comment by vitojeng** [comment]
> @vitojeng the branch name consisting of only number will confuse git that it tries to make the code base checkout to a "commit hash" than "branch". Could you file another PR with suitable branch name?

Sure. Thanks @chia7712 !

**Comment by vitojeng** [comment]
see #1883

**Pull request closed without merging**
