### PR TITLE
#5575 RowSourceTask#commitRecord should apply lazy field initialization

### LINKED ISSUE #5575: RowSourceTask#commitRecord should apply lazy field initialization
```RowSourceTask#commitRecord``` has to convert kafka record to ohara record. The conversion is not cheap so we should apply lazy operation to avoid useless cost.

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist

- [ ] [Review Contribution Guidelines](https://oharastream.github.io/en/docs/master/contributing/)
- [ ] Add at least one reviewer (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [ ] Add an assignee (of course, you are the assignee by default)
- [ ] Do not set milestone, projects and labels (PR labels are added automatically by Jenkins)
- [ ] Link to an issue fix #5575
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (If the failed tests are unrelated to this PR, add a comment in the PR thread)

### CODE REVIEW

**Review by jackyoh — APPROVED** [review]

**Comment by jackyoh** [comment]
retry connectorIT

**Comment by chia7712** [comment]
> This PR may break API compatibility!!!

沒事，只是我中斷QA而已 :(

**Comment by chia7712** [comment]
retry collieIT

**Comment by chia7712** [comment]
retry configurator

**Comment by chia7712** [comment]
retry configurator

**Comment by chia7712** [comment]
retry collieIT

**Pull request merged**
