### PR TITLE
#5510 [Manager] Avoid directly closing the DeleteWorkspace dialog

### PR DESCRIPTION
**Pull request by eechih**
### Checklist

- [x] [Review Contribution Guidelines](https://oharastream.github.io/en/docs/master/contributing/)
- [x] Add at least one reviewer (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add an assignee (of course, you are the assignee by default)
- [x] Do not set milestone, projects and labels (PR labels are added automatically by Jenkins)
- [x] Link to an issue #5510 
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (If the failed tests are unrelated to this PR, add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
Could you add relative test cases for the changes?

**Comment by eechih** [comment]
> Could you add relative test cases for the changes?

Sure :)

**Comment by eechih** [comment]
retry manager-it

**Comment by eechih** [comment]
retry manager-e2e

**Pull request merged**
