### PR TITLE
#4346 add "nodeMetrics" instead of "metrics" to display metrics of ea…

### PR DESCRIPTION
**Pull request by chia7712**
…ch node

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4346)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by jackyoh** [comment]
很像 TestConsoleSinkTask#configs map 的 name 要改成 connectorKey，因為我看到有些測試會丟出 connectorKey doesn't exist 的錯誤

**Comment by chia7712** [comment]
> 很像 TestConsoleSinkTask#configs map 的 name 要改成 connectorKey，因為我看到有些測試會丟出 connectorKey doesn't exist 的錯誤

@jackyoh thanks for the reminder. Let me address it via next commit.

**Comment by chia7712** [comment]
retry otherIT

**Comment by chia7712** [comment]
the flaky ```TestVersionFile``` is traced by #4446

**Comment by jackyoh** [comment]
retry otherIT

**Pull request merged**
