### PR TITLE
#1614 Bump akka dependencies

### PR DESCRIPTION
**Pull request by vitojeng**
required by #1614

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by jackyoh** [comment]
這個 PR 看起來是 akka 版本的升級。

**Comment by vitojeng** [comment]
> 這個 PR 看起來是 akka 版本的升級。

yep :)

**Comment by vitojeng** [comment]
retry configurator

**Comment by vitojeng** [comment]
retry connectorIT

**Comment by vitojeng** [comment]
retry connectorIT

**Pull request merged**
