### PR TITLE
#1381 Bump kafka version from 2.2.0 to 2.2.1

### PR DESCRIPTION
**Pull request by vitojeng**
required by #1381 

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by vitojeng** [comment]
retry it

**Comment by vitojeng** [comment]
> Please rebuild and push the deps image after merging this PR.

OK!

**Comment by vitojeng** [comment]
retry it

**Comment by jackyoh** [comment]
retry it

**Comment by jackyoh** [comment]
retry it

**Comment by jackyoh** [comment]
retry it

**Comment by vitojeng** [comment]
Thank @chia7712 and @jackyoh for the great support!

**Pull request merged**
