### PR TITLE
#1002 Jenkins should save e2e failed test screenshots

### PR DESCRIPTION
**Pull request by chia7712**
This PR is used to test #1002. see what is packaged by our jenkins

### CODE REVIEW

**Comment by chia7712** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
@chia7712 Where do you plan to store these screenshots?

**Comment by chia7712** [comment]
> here do you plan to store these screenshots?

master-jenkins. However, seems jenkins doesn't store screenshots correctly...

**Comment by chia7712** [comment]
retry manager

**Pull request closed without merging**
