### PR TITLE
#1674 the generated default value from JsonRefiner is constant than r…

### PR DESCRIPTION
**Pull request by chia7712**
…andom

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1674)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
reviewers and assignees? :)

**Comment by chia7712** [comment]
> reviewers and assignees? :)

done!!!

**Comment by jackyoh** [comment]
這個 PR 會合併到 master 嗎？

**Comment by chia7712** [comment]
> 這個 PR 會合併到 master 嗎？

see #1675

**Comment by chia7712** [comment]
retry manager-api

**Comment by jackyoh** [comment]
> see #1675

OK, 了解了

**Comment by chia7712** [comment]
retry manager-api

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Pull request merged**
