### PR TITLE
#1593 Connector validation fails with a missing name field error

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1593)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
@chia7712 @wu87988622 

The `name` and `connector.class` keys are now disabled (read-only). These keys shouldn't be edited from the UI perspective

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry manager-api

**Comment by konekoya** [comment]
retry manager-api

**Comment by chia7712** [comment]
@konekoya 

The tmp configurator is based on you PR without rebase so you have to rebase you PR in order to include the fix to flaky manager-api. BTW, this is a todo to our jenkins.

**Comment by konekoya** [comment]
> The tmp configurator is based on you PR without rebase so you have to rebase you PR in order to include the fix to flaky manager-api. BTW, this is a todo to our jenkins.

Thanks! Sounds like a pro tip that I should have learned...

**Comment by chia7712** [comment]
@konekoya FYI #1629

**Comment by konekoya** [comment]
Merging this as the build error is not related

**Pull request merged**
