### PR TITLE
#874 Make sure CI can run frontend e2e tests with gradle it command

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #874 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
/cc @chia7712 

```sh
gradle it -Pconfigurator=http://10.1.13.102:12345/v0 -Pport=5050 -PnodeHost=http://10.1.13.103 -PnodePort=22 -PnodeUser=ohara -PnodePass=island123
```

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
@chia7712 Is this PR ready to merge :)

**Pull request merged**
