### PR TITLE
test_2449

### PR DESCRIPTION
**Pull request by chia7712**
for testing the docs site exposed by jenkins :)

changes:

1. the link to makedoc is either the docs site or log. the first is for the perfect docs and the later is for the PR making warnings to our docs.
1. the link to javadoc is log (we don't have javadoc site yet)
1. the link to scaladoc is log (we don't have scaladocsite yet)

required by #2449

### CODE REVIEW

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
@oharastream/developer please take a look :)

**Comment by vitojeng** [comment]
Thanks @chia7712! Overall pretty good.  

Just two places are a bit strange:
* Why the logo image so large?
* Why all of the icons disappear?

**Comment by jackyoh** [comment]
Thank you @chia7712

**Comment by chia7712** [comment]
> Why the logo image so large?
> Why all of the icons disappear?

Actually, I have no idea totally since all artifacts are generated by “make html” :(

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
> Why the logo image so large?
Why all of the icons disappear?

from [here](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy). Seems jenkins has some limits on html.

**Comment by chia7712** [comment]
@oharastream/developer I'm not familiar with the css/js so opening the csp is not adequate solution to me. I have skimmed over the docs site, and the view is ok to me. So any feedback?

**Comment by vitojeng** [comment]
For preview in the PR phase, it's fine to me.
Thanks for digging this. 👍

**Comment by chia7712** [comment]
@oharastream/developer the changes is in jenkins now. I'm about to close this PR.

**Pull request closed without merging**
