### PR TITLE
#1775 Merge AccessOfProperty and ActionAccess class of StreamApi

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1775)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
/cc @wu87988622 
this pr will **need** the manager change :
```diff
- /v0/api/stream/property
+ /v0/api/stream
```

**Comment by saivirtue** [comment]
retry

**Comment by saivirtue** [comment]
retry

**Comment by wu87988622** [comment]
retry

**Comment by saivirtue** [comment]
retry

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
retry common

**Comment by chia7712** [comment]
retry common

**Comment by saivirtue** [comment]
retry it

**Comment by chia7712** [comment]
@saivirtue 可以清理一下節點後再跑IT

**Comment by saivirtue** [comment]
retry

**Comment by saivirtue** [comment]
retry it

**Comment by saivirtue** [comment]
The failed it tests are unrelated, merge now

**Pull request merged**
