### PR TITLE
#3339 DockerClient/K8SClient should ignore the containers created by other one

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #3339)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry sshConfigurator

**Comment by chia7712** [comment]
retry k8sConfigurator

**Comment by jackyoh** [comment]
retry configurator

**Comment by jackyoh** [comment]
這個 PR 要 merge 到 master 了嗎？因為如果我把 issue #3338 merge 進去之後 K8SClient.scala 的程式碼會有衝突

**Comment by chia7712** [comment]
> 這個 PR 要 merge 到 master 了嗎？因為如果我把 issue #3338 merge 進去之後 K8SClient.scala 的程式碼會有衝突

this issue is blocked by #3355 :(

It is ok to merge #3338 first :)

**Comment by jackyoh** [comment]
> this issue is blocked by #3355 :(
> 
> It is ok to merge #3338 first :)

OK, Thank you.

**Comment by chia7712** [comment]
the error is traced by #3368 and #3365

**Pull request merged**
