### PR TITLE
#4460 add ClusterState to both of ClusterInfo and ClusterStatus

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4460)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry connectorIT

**Comment by chia7712** [comment]
retry otherIT

**Comment by chia7712** [comment]
retry collieIT

**Comment by jackyoh** [comment]
retry collieIT

**Comment by chia7712** [comment]
retry otherIT

**Comment by chia7712** [comment]
retry otherIT

**Comment by chia7712** [comment]
```
2020-04-19 05:28:54,494 ERROR [scala-execution-context-global-25] docker.DockerClient$$anon$1(235): failed to get container names from ohara-jenkins-it-00
java.lang.IllegalStateException: SshClient not started. Please call start() method before connecting to a server
	at org.apache.sshd.client.SshClient.doConnect(SshClient.java:557)
	at org.apache.sshd.client.SshClient.connect(SshClient.java:505)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:134)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:115)
	at org.apache.sshd.client.simple.AbstractSimpleClientSessionCreator$1.connect(AbstractSimpleClientSessionCreator.java:158)
	at org.apache.sshd.client.simple.AbstractSimpleClientSessionCreator.sessionLogin(AbstractSimpleClientSessionCreator.java:77)
	at org.apache.sshd.client.simple.SimpleSessionClient.sessionLogin(SimpleSessionClient.java:117)
	at org.apache.sshd.client.simple.SimpleSessionClient.sessionLogin(SimpleSessionClient.java:63)
	at oharastream.ohara.agent.Agent$Builder$$anon$1.execute(Agent.scala:123)
```

Let me trace it on another issue

**Pull request merged**
