### PR TITLE
#5078 [Manager] The dragging icon of component in toolbox display inc…

### PR DESCRIPTION
**Pull request by konekoya**
…orrect

### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #5078)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
@vitojeng Could you help test this PR out see if the behavior is working like what you expected? 🙏

**Comment by vitojeng** [comment]
> @vitojeng Could you help test this PR out see if the behavior is working like what you expected? 🙏

I use firefox, still have the same issue.

**Comment by konekoya** [comment]
retry manager-e2e

**Comment by konekoya** [comment]
> I use firefox, still have the same issue.

The issue has been resolved by this PR :)

**Pull request merged**
