### PR TITLE
#2882 Update UI test case 1

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #2882)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
@saivirtue could you help me with the code style check...

https://builds.is-land.com.tw/view/oharastream/job/PreCommit-OHARA/6086/artifact/checks/check_build.log

**Comment by chia7712** [comment]
> could you help me with the code style check...

```gradle spotlessApply```

**Comment by konekoya** [comment]
> gradle spotlessApply

Does it also work for markdown files? Hmm, let me give it a try...

**Comment by saivirtue** [comment]
> Does it also work for markdown files? Hmm, let me give it a try...

markdown format checking will need using `make html` in `/docs`

**Comment by konekoya** [comment]
> markdown format checking will need using make html in /docs

That's weird. `gradle spotlessApply` somehow fixed my style issue 😅

**Comment by chia7712** [comment]
> somehow fixed my style issue sweat_smile

the style error you encountered is about scala code rather than markdown file

**Comment by konekoya** [comment]
> the style error you encountered is about scala code rather than markdown file

Ah, good catch @chia7712. This file shouldn't be committed at all. It's in one of our test case's steps and so only the markdown file should be checked in not this scala file 😨

**Pull request merged**
