### PR TITLE
#5085 [Manager] Highlight information about unavailable nodes

### PR DESCRIPTION
**Pull request by eechih**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #5085 )
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by eechih** [comment]
@vitojeng Preview screen

螢幕快照 2020-05-27 下午5 49 30

**Comment by konekoya** [comment]
@eechih nicely done 💯 Just I would change the Tooltip message to:

_Ohara-dev-09 node doesn’t have any running container. Cause: ohara-dev-09 node doesn’t exist_

**Comment by eechih** [comment]
> Just I would change the Tooltip message to:

> Ohara-dev-09 node doesn’t have any running container. Cause: ohara-dev-09 node doesn’t exist

message 是 api 回傳，要請 @chia7712 幫忙修改

**Comment by konekoya** [comment]
This explains why i didn't see the message in our source...

**Comment by chia7712** [comment]
要改訊息嗎？

**Comment by eechih** [comment]
> 要改訊息嗎？

@chia7712 0.10.0 先不用改

**Comment by eechih** [comment]
retry manager-e2e

**Comment by eechih** [comment]
retry manager-e2e

**Comment by eechih** [comment]
retry manager-e2e

**Pull request merged**
