### PR TITLE
#1840 Convert format from md to rst: contributing, how_to_build

### PR DESCRIPTION
**Pull request by vitojeng**
required by #1840 

Preview:
* https://vitojeng-ohara.readthedocs.io/en/docs/contributing.html
* https://vitojeng-ohara.readthedocs.io/en/docs/how_to_build.html

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@vitojeng how to preview this PR?

**Comment by vitojeng** [comment]
> @vitojeng how to preview this PR?

Yep, just update the description.

**Comment by vitojeng** [comment]
After the PR, I need to wait for the build to succeed before I can fill in the preview URL.

**Comment by chia7712** [comment]
@vitojeng Could you add ```gradle licenseApply``` to contributing.rst in this PR?

**Comment by vitojeng** [comment]
> @vitojeng Could you add `gradle licenseApply` to contributing.rst in this PR?

@chia7712 My bad. Totally forget license header.
It would be better we add **.rst** file support to licenseApply first.
I would submit another PR to complete **.rst** support before this PR merged.

**Comment by vitojeng** [comment]
> I would submit another PR to complete **.rst** support before this PR merged.

Already completed in the pull request #1884

**Pull request merged**
