### PR TITLE
#5301 add the testing report type of json-summary to QA

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://oharastream.github.io/en/docs/master/contributing/)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #5301)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
Only changing json file
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by saivirtue** [comment]
retry manager-it

**Comment by saivirtue** [comment]
> Nice, plain text for the report?

Yep, for our uncle Jenkins to do the parser 😄 
example:
```
=============================== Coverage summary ===============================
Statements   : 100% ( 166/166 )
Branches     : 75% ( 18/24 )
Functions    : 100% ( 49/49 )
Lines        : 100% ( 161/161 )
================================================================================
```

**Comment by jackyoh** [comment]
@saivirtue  可以提供 Coverage summary  的檔案路徑資訊嗎？

**Comment by saivirtue** [comment]
> @saivirtue 可以提供 Coverage summary 的檔案路徑資訊嗎？

Sure. I'll give it to you later.

**Comment by saivirtue** [comment]
retry manager-it

**Comment by jackyoh** [comment]
retry manager-it

**Comment by jackyoh** [comment]
retry manager-it

**Pull request merged**
