### PR TITLE
#1873 Remove enzyme lib from  pipeline list page 

### PR DESCRIPTION
**Pull request by DavidMi-1**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1873)
- [x] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
@DavidMi-1 I'm seeing a warning... is this something that you cannot resolve by yourself

```js
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sources' of undefined
```

**Comment by DavidMi-1** [comment]
> @DavidMi-1 I'm seeing a warning... is this something that you cannot resolve by yourself
> 
> ```js
> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sources' of undefined
> ```

trying to resolve it

**Comment by DavidMi-1** [comment]
@konekoya resolve warning and others, pls review again :)

**Comment by konekoya** [comment]
retry makedoc

**Comment by konekoya** [comment]
retry docs

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
I've done some refactoring. Thanks for the contribution @DavidMi-1 :)

**Comment by DavidMi-1** [comment]
> I've done some refactoring. Thanks for the contribution @DavidMi-1 :)

thanks for the refactor and merge :)

**Pull request merged**
