### PR TITLE
OHARA-1467 Remove unused line in start-service.sh

### PR DESCRIPTION
**Pull request by vitojeng**

### CODE REVIEW

**Comment by vitojeng** [comment]
Note: Jira issue OHARA-1293 number was wrong, should be OHARA-1467.
Remember correct it when merging into master,

**Comment by chia7712** [comment]
為了以防萬一，可否麻煩你基於這個PR去建立configurator image，然後試著跑跑看是否有正確抓到script? 謝謝

**Comment by chia7712** [comment]
`docker build --no-cache --build-arg REPO={your_repo} --build-arg BRANCH={your_branch} -f ./configurator.dockerfile -t oharastream/configurator:0.2-SNAPSHOT .`

**Comment by vitojeng** [comment]
> 為了以防萬一，可否麻煩你基於這個PR去建立configurator image，然後試著跑跑看是否有正確抓到script? 謝謝

Done. It works perfectly well.

**Pull request merged**
