### PR TITLE
#298 Add test connection button in HDFS sink prop form

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #issue_number)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

required by #298

### CODE REVIEW

**Comment by konekoya** [comment]
I think we'll need to wait for #491 merging in

**Comment by chia7712** [comment]
> I think we'll need to wait for #491 merging in

wait a minute :(

**Comment by konekoya** [comment]
@chia7712  As #494 was merged. Can I merge this PR now :)

**Comment by chia7712** [comment]
> As #494 was merged. Can I merge this PR now :)

Have you test it on local?

**Comment by konekoya** [comment]
> Have you test it on local?
Ah, right. I somehow forgot this...

**Comment by konekoya** [comment]
@chia7712 Tested on my machine, the success request worked great. However, the failed request's message field seemed to be an empty string?

**Comment by chia7712** [comment]
> Tested on my machine, the success request worked great. However, the failed request's message field seemed to be an empty string?

How to reproduce this issue?

**Pull request merged**
