### PR TITLE
#4419 [Manager] Introduce react-redux instead of redux-react-hook

### PR DESCRIPTION
**Pull request by eechih**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #4419)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by eechih** [comment]
retry manager-api

**Comment by konekoya** [comment]
@eechih could you explain a little bit why we're switching from `react-redux-hook` to `react-redux`

**Comment by eechih** [comment]
> Maybe this is the answer...
https://github.com/facebookincubator/redux-react-hook#how-does-this-compare-to-react-redux

@konekoya 感謝你的補充。另外，我將 redux-react-hook 換成 react-redux 的原因是為了能讓 redux-form 順利 connect to store。

**Comment by eechih** [comment]
test/manager-api error 與這個 PR 沒有關係，會建立一個 issue 來處理 test/manager-api error。

**Pull request merged**
