### PR TITLE
#1484 Check if the build dir is exist when running end-to-end tests

### PR DESCRIPTION
**Pull request by konekoya**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1484)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by konekoya** [comment]
retry manager-it

**Comment by konekoya** [comment]
retry manager-it

**Comment by konekoya** [comment]
> can you add to runApiTest.js too? api test also need.

No problem. But it seems to have some problem running the test. I'll need to take a look and fix that first :)

**Comment by wu87988622** [comment]
> > can you add to runApiTest.js too? api test also need.
> 
> No problem. But it seems to have some problem running the test. I'll need to take a look and fix that first :)

ok, thank for this PR.

**Comment by chia7712** [comment]
@konekoya I'm going to test jenkins via this PR :)

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
@wu87988622 @konekoya Please take a look at this [build](https://builds.is-land.com.tw/job/PreCommit-OHARA/2873/console). Testing manager, now, invokes image sync also.

**Comment by konekoya** [comment]
retry manager-it

**Pull request merged**
