### PR TITLE
OHARA-1624 [Configurator] On FTP connector, empty properties should b…

### PR DESCRIPTION
**Pull request by saivirtue**
…e handled

### CODE REVIEW

**Comment by saivirtue** [comment]
retry

**Comment by chia7712** [comment]
The new tests are great. However, could you add UT for toMap() only.

**Comment by saivirtue** [comment]
> The new tests are great. However, could you add UT for toMap() only.

do you mean the property test part?

**Comment by chia7712** [comment]
> do you mean the property test part?

yep

**Comment by saivirtue** [comment]
done.

**Pull request merged**
