### PR TITLE
#431 add task of publishing artifacts to jfrog

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] Set a Milestone (we usually file PR for master branch)
- [x] Link to an issue(You can do so by using the required by keyword: required by #431)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
      (I have test this PR manually)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@saivirtue Please sing up a jfrog account and then test this PR :)

**Comment by saivirtue** [comment]
> @saivirtue Please sing up a jfrog account and then test this PR :)

OK, I will let you know the good result ;)

**Comment by chia7712** [comment]
@saivirtue Could you try to publish artifacts to our official repo (see https://bintray.com/beta/#/oharastream/ohara?tab=packages) ? You are our 0.3 RM so it would be better to let you be able to access the repo asap.

**Comment by saivirtue** [comment]
> @saivirtue Could you try to publish artifacts to our official repo (see https://bintray.com/beta/#/oharastream/ohara?tab=packages) ? You are our 0.3 RM so it would be better to let you be able to access the repo asap.

I will need some information to accomplish this, right? 
[] create packages (ohara-*)
[] get the user/key api access

**Comment by chia7712** [comment]
> I will need some information to accomplish this, right?
not really. What you need is write permission.

@vitojeng  Could you add @saivirtue to our maven repo?

**Comment by chia7712** [comment]
seems vito is busy now. @saivirtue Please give me you jfrog account

**Pull request merged**
