### PR TITLE
#1026 Enable streamApp image to show the revision

### PR DESCRIPTION
**Pull request by saivirtue**
### Checklist
- [x] [Review Contribution Guidelines](https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#authors))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #1026)
- [ ] Add unit tests (or please explain why this PR is not worth having new tests)
- [x] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
@saivirtue Please test this PR locally since our jenkins can't verify this PR for us :(

**Comment by saivirtue** [comment]
> @saivirtue Please test this PR locally since our jenkins can't verify this PR for us :(

Should I pass the result of local tests?

**Comment by chia7712** [comment]
> Should I post the result of local tests?

We all know this PR works well on you local when you merge it.

**Comment by saivirtue** [comment]
> We all know this PR works well on you local when you merge it.

Merge = testing local = all good ?

**Comment by chia7712** [comment]
> Merge = testing local = all good ?

yep :)

**Pull request merged**
