### PR TITLE
#3990 Integrate ConnectorVersion with WithDefinition

### PR DESCRIPTION
**Pull request by chia7712**
### Checklist
- [x] [Review Contribution Guidelines](https://ohara.readthedocs.io/en/latest/contributing.html)
- [x] Add Reviewers (see [Authors](https://github.com/oharastream/ohara#ohara-team))
- [x] Add Assignees (of course, you are the assignee by default!)
- [x] DON'T set a Milestone
- [x] DON'T add any labels (PR labels will be added automatically by Jenkins)
- [x] Link to an issue(You can do so by using the required by keyword: required by #3990)
- [ ] Pass QA (Sometimes you may encounter an existing flaky test which would obstruct you from getting QA passed. If the failed tests are unrelated, you can add a comment in the PR thread)

### CODE REVIEW

**Comment by chia7712** [comment]
retry

**Comment by jackyoh** [comment]
這個 PR 的目的是，新版的 kafka 已經有提供 connector 相關的資訊，像是 version 和 author 所以之前的 ConnectorVersion  就被刪除了。在 RowSourceConnector 和 RowSinkConnector override version 和 author 的方法，應該是屬於 kafka 的部份吧。

**Comment by chia7712** [comment]
> 這個 PR 的目的是，新版的 kafka 已經有提供 connector 相關的資訊，像是 version 和 author 所以之前的 ConnectorVersion 就被刪除了。在 RowSourceConnector 和 RowSinkConnector override version 和 author 的方法，應該是屬於 kafka 的部份吧。

for another, we are going to have an interface for managing all services (including connector, stream and shabondi). Hence, the stuff embedded on connector have to be integrated to the interface.

The next PR will apply the interface on stream and shabondi

**Comment by chia7712** [comment]
retry

**Comment by chia7712** [comment]
unrelated error

**Pull request merged**
