### PR TITLE
Add some comment in README.md

### PR DESCRIPTION
**Pull request by konekoya**

### CODE REVIEW

**Comment by konekoya** [comment]
Testing

**Comment by konekoya** [comment]
Reponed, I'm going to test the "run" command in this PR

**Comment by konekoya** [comment]
retry manager

**Comment by konekoya** [comment]
retry common

**Comment by konekoya** [comment]
run

**Comment by g1geordie** [comment]
123

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
response

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
response

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
response from jenkins

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
response from jenkins

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
response from jenkins

**Comment by g1geordie** [comment]
test

**Comment by g1geordie** [comment]
test

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
response from jenkins

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
http://10.1.0.102:30008 is initializing, this may take a few minutes

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
http://10.1.0.102:30009 is initializing, this may take a few minutes

**Comment by g1geordie** [comment]
run swagger -c

**Comment by g1geordie** [comment]
http://10.1.0.102:30010 is initializing, this may take a few minutes

**Comment by g1geordie** [comment]
run swagger -c

**Comment by g1geordie** [comment]
http://10.1.0.102:30011 is initializing, this may take a few minutes

**Comment by konekoya** [comment]
Good job, @g1geordie

**Comment by chia7712** [comment]
Do we have public IPs for those services?

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
http://10.1.0.102:30012 is initializing, this may take a few minutes

**Comment by g1geordie** [comment]
> Do we have public IPs for those services?

sounds like we need to start a proxy server at public ip server to handle those request

**Comment by chia7712** [comment]
> sounds like we need to start a proxy server at public ip server to handle those request

How about [ngrok](https://ngrok.com/) ?

**Comment by g1geordie** [comment]
http://10.1.0.102:30014 is initializing, this may take a few minutes

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger

**Comment by g1geordie** [comment]
run swagger -c

**Comment by g1geordie** [comment]
run swagger -c

**Comment by g1geordie** [comment]
run swagger -c

**Comment by konekoya** [comment]
run swagger

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by g1geordie** [comment]
run swagger -l

**Comment by konekoya** [comment]
run

**Comment by g1geordie** [comment]
run swagger -l

**Comment by g1geordie** [comment]
run swagger -l

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by g1geordie** [comment]
run swagger -l

**Comment by g1geordie** [comment]
run swagger -l

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run swagger -c

**Comment by konekoya** [comment]
run

**Comment by g1geordie** [comment]
run swagger -c

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by g1geordie** [comment]
run swagger -c

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
run manager

**Comment by konekoya** [comment]
run

**Comment by konekoya** [comment]
Finish testing run command. Big thanks to @g1geordie :)

**Pull request closed without merging**
